name: esimcardsdk
description: ESIMCARD SDK for Flutter offers a powerful toolkit for developers to integrate ESIMCARD services seamlessly into their Flutter applications. With this SDK, developers can access a range of functionalities, enabling robust and efficient interactions with ESIMCARD APIs, enhancing the capabilities of Flutter apps with ease.
version: 0.0.6
homepage: https://codiea.io/
repository: https://github.com/Codiea/flutter_esimcard_sdk

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.1.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
